// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2468.Test_Swerve.subsystems;

import org.usfirst.frc2468.Test_Swerve.RobotMap;
import org.usfirst.frc2468.Test_Swerve.commands.*;

import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class TestDrive extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final WPI_TalonSRX azimuth0 = RobotMap.Azimuth0;
    private final WPI_TalonSRX azimuth1 = RobotMap.Azimuth1;
    private final WPI_TalonSRX azimuth2 = RobotMap.Azimuth2;
    private final WPI_TalonSRX azimuth3 = RobotMap.Azimuth3;
    private final WPI_TalonSRX drive0 = RobotMap.Drive0;
    private final WPI_TalonSRX drive1 = RobotMap.Drive1;
    private final WPI_TalonSRX drive2 = RobotMap.Drive2;
    private final WPI_TalonSRX drive3 = RobotMap.Drive3;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
    	
    	encoderReport(azimuth0);
    	encoderReport(azimuth1);
    	encoderReport(azimuth2);
    	encoderReport(azimuth3);
    	encoderReport(drive0);
    	encoderReport(drive1);
    	encoderReport(drive2);
    	encoderReport(drive3);


    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    public void encoderReport(WPI_TalonSRX talon) {
    	SmartDashboard.putNumber(talon.getName(), talon.getSelectedSensorPosition(0));
    }

}

