// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2468.Test_Swerve;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX Azimuth0;
    public static WPI_TalonSRX Azimuth1;
    public static WPI_TalonSRX Azimuth2;
    public static WPI_TalonSRX Azimuth3;
    public static WPI_TalonSRX Drive0;
    public static WPI_TalonSRX Drive1;
    public static WPI_TalonSRX Drive2;
    public static WPI_TalonSRX Drive3;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        Azimuth0 = new WPI_TalonSRX(0);
        
        
        Azimuth1 = new WPI_TalonSRX(1);
        
        
        Azimuth2 = new WPI_TalonSRX(2);
        
        
        Azimuth3 = new WPI_TalonSRX(3);
        
        
        Drive0 = new WPI_TalonSRX(10);
        
        
        Drive1 = new WPI_TalonSRX(11);
        
        
        Drive2 = new WPI_TalonSRX(12);
        
        
        Drive3 = new WPI_TalonSRX(13);
        
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
